### ISSUE TITLE
hvswitchon not working

### ISSUE THREAD

**Issue by marcocasolino** [cescalara/minieuso_cpu#69]
Hi Francesca,
also mecontrol -hvswitch on
does not work. it gets stuck here
[hvswitchon.txt](https://github.com/cescalara/minieuso_cpu/files/3179031/hvswitchon.txt)

note that hvswitch off works (!)
thanks

**Comment by cescalara** [comment]
Hi Marco, 

While I can't be sure from what you've sent, to me it looks like you have used the command:
`mecontrol -hvswitch on` 

In order to specify which Eps you want to switch on, you need another input, eg.:
`mecontrol -hvswitch on -hv all`

as per the docs -> [here](https://minieuso-software.readthedocs.io/en/latest/usage/functionality.html#control-of-the-high-voltage-hv).

I'll leave this open for now and let me know if this is not the case.

Cheers

**Comment by marcocasolino** [comment]
uuuhhhh sorry!
m

**Comment by cescalara** [comment]
I updated the `mecontrol -help` output as this is probably what confused you :)
